// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL01fQCq5L53wBGbcGnkvWUCsDHht9XY0',
    appId: '1:822580330966:web:286d54923aad15aaeb6477',
    messagingSenderId: '822580330966',
    projectId: 'todoapp-f188c',
    authDomain: 'todoapp-f188c.firebaseapp.com',
    storageBucket: 'todoapp-f188c.appspot.com',
    measurementId: 'G-TC1DME7P5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY9EcQEY34bqPUFWhrj2DtFUfF4ZVtN9k',
    appId: '1:822580330966:android:8b7bbf57854b20a5eb6477',
    messagingSenderId: '822580330966',
    projectId: 'todoapp-f188c',
    storageBucket: 'todoapp-f188c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXWDK7x52DRBD2iIVrGAQqstePfaBqv1U',
    appId: '1:822580330966:ios:8bd4ebc54fba05c1eb6477',
    messagingSenderId: '822580330966',
    projectId: 'todoapp-f188c',
    storageBucket: 'todoapp-f188c.appspot.com',
    iosBundleId: 'com.example.untitled30',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXWDK7x52DRBD2iIVrGAQqstePfaBqv1U',
    appId: '1:822580330966:ios:8bd4ebc54fba05c1eb6477',
    messagingSenderId: '822580330966',
    projectId: 'todoapp-f188c',
    storageBucket: 'todoapp-f188c.appspot.com',
    iosBundleId: 'com.example.untitled30',
  );
}
